"""Type stubs for pyrox - PyO3 bindings for Wellen waveform library."""

from typing import Optional, Iterator, List, Tuple, Union, Literal, Dict, Any, Callable, TypedDict
from typing_extensions import Self, NotRequired

# Type aliases for clarity
Time = int
SignalValue = Union[int, str, float]
SignalHandle = int

# Async event types
class HeaderStartLoadEvent(TypedDict):
    """Event emitted when header loading starts."""
    type: Literal["HeaderStartLoad"]

class HeaderLoadedEvent(TypedDict):
    """Event emitted when header is fully loaded."""
    type: Literal["HeaderLoaded"]
    hierarchy: NotRequired[Hierarchy]

class BodyStartLoadEvent(TypedDict):
    """Event emitted when body loading starts."""
    type: Literal["BodyStartLoad"]

class BodyLoadedEvent(TypedDict):
    """Event emitted when body is fully loaded."""
    type: Literal["BodyLoaded"]
    time_table: NotRequired[TimeTable]

class SignalStartLoadEvent(TypedDict):
    """Event emitted when signal loading starts."""
    type: Literal["SignalStartLoad"]
    handles: List[SignalHandle]

class SignalLoadedEvent(TypedDict):
    """Event emitted when signals are loaded."""
    type: Literal["SignalLoaded"]
    signals: List[Tuple[SignalHandle, Signal]]

class AsyncErrorEvent(TypedDict):
    """Event emitted when an error occurs during async loading."""
    type: Literal["Error"]
    error: str

# Union of all async event types
AsyncEvent = Union[
    HeaderStartLoadEvent,
    HeaderLoadedEvent,
    BodyStartLoadEvent,
    BodyLoadedEvent,
    SignalStartLoadEvent,
    SignalLoadedEvent,
    AsyncErrorEvent,
]

# Callback type for async events
AsyncCallback = Callable[[AsyncEvent], None]

class VarIndex:
    """Variable bit range index."""
    def msb(self) -> int: ...
    def lsb(self) -> int: ...

class Var:
    """Variable/signal in the hierarchy."""
    def name(self, hier: Hierarchy) -> str: ...
    def full_name(self, hier: Hierarchy) -> str: ...
    def scope_path(self, hier: Hierarchy) -> List[str]: ...
    def bitwidth(self) -> Optional[int]: ...
    def var_type(self) -> str: ...
    def enum_type(self, hier: Hierarchy) -> Optional[Tuple[str, List[Tuple[str, str]]]]: ...
    def vhdl_type_name(self, hier: Hierarchy) -> Optional[str]: ...
    def direction(self) -> str: ...
    def length(self) -> Optional[int]: ...
    def is_real(self) -> bool: ...
    def is_string(self) -> bool: ...
    def is_bit_vector(self) -> bool: ...
    def is_1bit(self) -> bool: ...
    def index(self) -> Optional[VarIndex]: ...
    def signal_handle(self) -> SignalHandle: ...

class VarIter:
    """Iterator over variables."""
    def __iter__(self) -> Self: ...
    def __next__(self) -> Var: ...

class Scope:
    """Scope (module, task, function, etc.) in the hierarchy."""
    def name(self, hier: Hierarchy) -> str: ...
    def full_name(self, hier: Hierarchy) -> str: ...
    def scope_type(self) -> str: ...
    def vars(self, hier: Hierarchy) -> VarIter: ...
    def scopes(self, hier: Hierarchy) -> ScopeIter: ...
    def is_record(self) -> bool: ...
    def record(self) -> Optional['Record']: ...

class ScopeIter:
    """Iterator over scopes."""
    def __iter__(self) -> Self: ...
    def __next__(self) -> Scope: ...

class TimeTable:
    """Time table with compressed time representation."""
    def __getitem__(self, idx: int) -> Time: ...
    def __len__(self) -> int: ...

class TimescaleUnit:
    """Timescale unit enumeration."""
    pass

class Timescale:
    """Timescale information."""
    unit: TimescaleUnit
    factor: int
    def to_str(self) -> str: ...
    def get_time_scale_factor_from_seconds(self) -> int: ...

class Hierarchy:
    """Design hierarchy."""
    def all_vars(self) -> VarIter: ...
    def top_scopes(self) -> ScopeIter: ...
    def find_var_by_path(self, path: List[str]) -> Optional[Var]: ...
    def get_var_by_signal_ref(self, handle: SignalHandle) -> Optional[Var]: ...
    def date(self) -> str: ...
    def version(self) -> str: ...
    def timescale(self) -> Optional[Timescale]: ...
    def file_format(self) -> Literal["VCD", "FST", "GHW", "JETS", "Unknown"]: ...

class SignalChangeIter:
    """Iterator over signal changes."""
    def __iter__(self) -> Self: ...
    def __len__(self) -> int: ...
    def __next__(self) -> Tuple[Time, SignalValue]: ...

class QueryResult:
    """Signal query result."""
    value: Optional[SignalValue]
    actual_time: Optional[Time]
    next_idx: Optional[int]
    next_time: Optional[Time]

class Signal:
    """Signal waveform data."""
    def value_at_time(self, time: Time) -> Optional[SignalValue]: ...
    def value_at_idx(self, idx: int) -> Optional[SignalValue]: ...
    def all_changes(self) -> SignalChangeIter: ...
    def all_changes_after(self, start_time: Time) -> SignalChangeIter: ...
    def query_signal(self, query_time: Time) -> QueryResult: ...
    def get_global_range(self, data_format: int, bit_width: int) -> Tuple[float, float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Waveform:
    """Main waveform reader with async loading support."""
    @property
    def hierarchy(self) -> Optional[Hierarchy]: ...

    @property
    def time_table(self) -> Optional[TimeTable]: ...

    def __init__(
        self,
        path: str,
        multi_threaded: bool = True,
        remove_scopes_with_empty_name: bool = False,
        load_header: bool = True,
        load_body: bool = True,
    ) -> None: ...

    def load_body(self) -> None: ...
    def body_loaded(self) -> bool: ...
    def header_loaded(self) -> bool: ...

    # Async API
    def set_async_callback(self, callback: Optional[AsyncCallback]) -> None: ...
    def load_header_async(
        self,
        multi_threaded: bool = True,
        remove_scopes_with_empty_name: bool = False
    ) -> None: ...
    def load_body_async(self) -> None: ...
    def load_signals_async(self, handles: List[SignalHandle]) -> None: ...

    # Signal loading API
    def get_signal_from_path(self, path_segments: List[str]) -> Signal: ...
    def get_signal_by_handle(self, handle: SignalHandle) -> Signal: ...
    def load_signals(self, vars: List[Var]) -> List[Signal]: ...

class Annotation:
    """Annotation attached to a record (name/value pair)."""
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> Any: ...

class TimedAnnotation:
    """Timed annotation (event occurring within a record's time range)."""
    @property
    def name(self) -> str: ...
    @property
    def time(self) -> Time: ...
    @property
    def value(self) -> Optional[Any]: ...

class Record:
    """JETS trace record."""
    def record_type(self) -> str:
        """Record type classification (e.g., "HostProgram", "KernelExecution", "Transaction")"""
        ...
    def name(self) -> str:
        """Record name (human-readable)"""
        ...
    def start_time(self) -> Time:
        """Start time in timescale units"""
        ...
    def end_time(self) -> Optional[Time]:
        """End time in timescale units (None if ongoing or unbounded)"""
        ...
    def annotations(self) -> List[Annotation]:
        """Annotations attached to this record (name/value pairs)"""
        ...
    def events(self) -> List[TimedAnnotation]:
        """Events occurring within this record's time range (timed annotations)"""
        ...
