"""Type stubs for pyrox - PyO3 bindings for Wellen waveform library."""

from typing import Optional, Iterator, List, Tuple, Union, Literal
from typing_extensions import Self

# Type aliases for clarity
Time = int
SignalValue = Union[int, str, float]
SignalHandle = int

class VarIndex:
    """Variable bit range index."""
    def msb(self) -> int: ...
    def lsb(self) -> int: ...

class Var:
    """Variable/signal in the hierarchy."""
    def name(self, hier: Hierarchy) -> str: ...
    def full_name(self, hier: Hierarchy) -> str: ...
    def bitwidth(self) -> Optional[int]: ...
    def var_type(self) -> str: ...
    def enum_type(self, hier: Hierarchy) -> Optional[Tuple[str, List[Tuple[str, str]]]]: ...
    def vhdl_type_name(self, hier: Hierarchy) -> Optional[str]: ...
    def direction(self) -> str: ...
    def length(self) -> Optional[int]: ...
    def is_real(self) -> bool: ...
    def is_string(self) -> bool: ...
    def is_bit_vector(self) -> bool: ...
    def is_1bit(self) -> bool: ...
    def index(self) -> Optional[VarIndex]: ...
    def signal_ref(self) -> SignalHandle: ...

class VarIter:
    """Iterator over variables."""
    def __iter__(self) -> Self: ...
    def __next__(self) -> Var: ...

class Scope:
    """Scope (module, task, function, etc.) in the hierarchy."""
    def name(self, hier: Hierarchy) -> str: ...
    def full_name(self, hier: Hierarchy) -> str: ...
    def scope_type(self) -> str: ...
    def vars(self, hier: Hierarchy) -> VarIter: ...
    def scopes(self, hier: Hierarchy) -> ScopeIter: ...

class ScopeIter:
    """Iterator over scopes."""
    def __iter__(self) -> Self: ...
    def __next__(self) -> Scope: ...

class TimeTable:
    """Time table with compressed time representation."""
    def __getitem__(self, idx: int) -> Time: ...
    def __len__(self) -> int: ...

class TimescaleUnit:
    """Timescale unit enumeration."""
    pass

class Timescale:
    """Timescale information."""
    unit: TimescaleUnit
    factor: int
    def to_str(self) -> str: ...
    def get_time_scale_factor_from_seconds(self) -> int: ...

class Hierarchy:
    """Design hierarchy."""
    def all_vars(self) -> VarIter: ...
    def top_scopes(self) -> ScopeIter: ...
    def date(self) -> str: ...
    def version(self) -> str: ...
    def timescale(self) -> Optional[Timescale]: ...
    def file_format(self) -> Literal["VCD", "FST", "GHW", "Unknown"]: ...

class SignalChangeIter:
    """Iterator over signal changes."""
    def __iter__(self) -> Self: ...
    def __len__(self) -> int: ...
    def __next__(self) -> Tuple[Time, SignalValue]: ...

class QueryResult:
    """Signal query result."""
    value: Optional[SignalValue]
    actual_time: Optional[Time]
    next_idx: Optional[int]
    next_time: Optional[Time]

class Signal:
    """Signal waveform data."""
    def value_at_time(self, time: Time) -> Optional[SignalValue]: ...
    def value_at_idx(self, idx: int) -> Optional[SignalValue]: ...
    def all_changes(self) -> SignalChangeIter: ...
    def all_changes_after(self, start_time: Time) -> SignalChangeIter: ...
    def query_signal(self, query_time: Time) -> QueryResult: ...

class Waveform:
    """Main waveform reader."""
    hierarchy: Hierarchy
    time_table: Optional[TimeTable]

    def __init__(
        self,
        path: str,
        multi_threaded: bool = True,
        remove_scopes_with_empty_name: bool = False,
        load_body: bool = True,
    ) -> None: ...

    def load_body(self) -> None: ...
    def body_loaded(self) -> bool: ...
    def get_signal(self, var: Var) -> Signal: ...
    def get_signal_from_path(self, abs_hierarchy_path: str) -> Signal: ...
    def get_signal_by_ref(self, signal_ref: SignalHandle) -> Signal: ...
    def load_signals(self, vars: List[Var]) -> List[Signal]: ...
    def load_signals_multithreaded(self, vars: List[Var]) -> List[Signal]: ...
    def load_signals_impl(self, vars: List[Var], multithreaded: bool) -> List[Signal]: ...
    def unload_signals(self, signals: List[Signal]) -> None: ...
